leftnav:
- identifier: ef18cd4e-46eb-c0ba-ef1d-d33f0317740b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e1b68388-4330-6972-a7ec-6bdd9f5174fd
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 3724b6b0-5599-facd-830c-ea7814517751
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  name: Lecture Notes
  url: /pages/lecture-notes/
  weight: 40
- identifier: 6a9441a2-bf72-e611-f1f2-516522e41ec1
  name: Reconstruction, Race, and Reunion
  parent: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  url: /pages/lecture-notes/lecture-2-reconstruction-race-and-reunion
  weight: 50
- identifier: f17cfc24-b97a-d31d-4c9d-842841861852
  name: Conflict and Conquest in the Frontier West
  parent: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  url: /pages/lecture-notes/conflict-and-conquest-in-the-frontier-west
  weight: 60
- identifier: 5518b486-f145-3e7a-c25f-89d7f3e12be5
  name: Capital, Labor, and the Standardization of Work
  parent: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  url: /pages/lecture-notes/lecture-6-capital-labor-and-the-standardization-of-work
  weight: 70
- identifier: fa2fbd01-93b7-a37b-e679-f9b30c07c185
  name: Becoming A World Power
  parent: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  url: /pages/lecture-notes/lecture-8-becoming-a-world-power
  weight: 80
- identifier: 618e5e86-65b8-28af-0b7f-1bda003c1924
  name: Progressive Reform
  parent: d8a46b5a-6f8b-fd32-4c55-64e4d12b9725
  url: /pages/lecture-notes/lecture-9-progressive-reform
  weight: 90
- identifier: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  name: Assignments
  url: /pages/assignments/
  weight: 100
- identifier: e5a1d5d5-035a-21de-6821-1f544ad90dbf
  name: Guidelines for Reading Responses
  parent: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  url: /pages/assignments/guidelines-for-reading-responses
  weight: 110
- identifier: 2b13e917-b8fe-e15f-b598-9ccb3b20f0b5
  name: 'Essay #1'
  parent: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  url: /pages/assignments/essay-1
  weight: 120
- identifier: 167eb069-c896-ee0e-7f7d-2d85aa615025
  name: 'Essay #2'
  parent: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  url: /pages/assignments/essay-2
  weight: 130
- identifier: a09371ad-1037-861a-3ad8-9108af4064db
  name: Choosing a Topic and Asking a Question
  parent: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  url: /pages/assignments/choosing-a-topic-and-asking-a-question
  weight: 140
- identifier: 19481ea7-fa46-20d5-5b6b-e1190a87e062
  name: Final Paper Proposal and Guidelines
  parent: fbb6e1b6-53bb-013c-4e01-d45c2ad75ee7
  url: /pages/assignments/final-paper-proposal-and-guidelines
  weight: 150
